export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  SET_NEW_PASSWORD: '/set-new-password/*',
  CHANGE_PASSWORD: '/change-password',
  ADMIN: '/admin',
  RESERVATIONS: '/reservations',
  RESERVATION: '/reservations/:id',
  HOME: '/dashboard',
  VEHICLES: '/vehicles',
  REPORTS: '/reports',
  CUSTOMERS: '/customers',
  EMPLOYEES: '/employees',
  // ADMIN_PROPERTIES: "/admin/properties",
  // ADMIN_CONSTRUCTIONS: "/admin/constructions",
};
